version: '3'
services:
  php:
    build: ./docker/php7
    working_dir: /app
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache
      - ./:/app
    ports:
      - '8082:8082'
      - '8000:80'
